name: Build RayTracer

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (jeśli są potrzebne, np. OpenGL, glm itp.)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libglm-dev 

    - name: Compile the RayTracer
      run: |
        # Tutaj wpisz komendy do kompilacji Twojego projektu.
        # Jeśli używasz CMake:
        mkdir build
        cd build
        cmake ..
        make
        # Jeśli kompilujesz bezpośrednio z g++ (przykładowo, dostosuj nazwy plików):
        # g++ -o rayTracer main.cpp some_other_file.cpp -I. -L/usr/local/lib -lraylib -std=c++17 # Przykładowa komenda
        # Jeśli masz skrypt kompilacji (np. compile.sh):
        # ./compile.sh

    - name: Run tests (opcjonalnie)
      run: 
