  create-release-and-upload-assets:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    permissions:
      contents: write

    steps:
      - name: Download Linux binary artifact
        uses: actions/download-artifact@v4
        with:
          name: rayTracer-linux
          path: ./artifacts/linux

      - name: Download Windows binary artifact
        uses: actions/download-artifact@v4
        with:
          name: rayTracer-windows
          path: ./artifacts/windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: <span class="math-inline">\{\{ secrets\.GITHUB\_TOKEN \}\}
with\:
tag\_name\: v</span>{{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
          draft: false
          prerelease: false

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: <span class="math-inline">\{\{ steps\.create\_release\.outputs\.upload\_url \}\}
asset\_path\: \./artifacts/linux/rayTracer
asset\_name\: rayTracer\-v</span>{{ github.run_number }}-linux
          asset_content_type: application/octet-stream

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: <span class="math-inline">\{\{ steps\.create\_release\.outputs\.upload\_url \}\}
asset\_path\: \./artifacts/windows/rayTracer\.exe
asset\_name\: rayTracer\-v</span>{{ github.run_number }}-windows.exe
          asset_content_type: application/octet-stream
